name: "LibreOffice Calc - Align Values"
level: "silver"
task: "You see the LibreOffice Calc open on the screen. Align the values in the table in the center. Use shortcuts to select the table. Save the document using a keyboard shortcut."
setup_cmd: "sudo apk add libreoffice && cd /config/Desktop && wget https://raw.githubusercontent.com/mariyadavydova/benchmark_data/main/demo_01.ods && setsid libreoffice --nologo demo_01.ods >/dev/null 2>&1 & sleep 2"
desktop_image: us-docker.pkg.dev/agentsea-dev/agentd/desktop-webtop:8ed7f4e
checks:
  - type: command_output
    command: "cd /config/Desktop && libreoffice --headless --convert-to html demo_01.ods && cat demo_01.html"
    value: "This is the content of the HTML document that was created from the LibreOffice Calc document that agent had to save. All cells with non-empty values in the first table (on the first sheet) should be aligned to the center. The cells in the second table (on the second sheet) DO NOT need to be aligned. If there are any other alignments or the alignment is incorrect, the test fails."
